[tool.importlinter]
root_package = "importlinter"

[[tool.importlinter.contracts]]
name="Layered architecture"
type="layers"
containers = [
    "importlinter"
]
layers=[
    "cli",
    "api",
    "contracts",
    "configuration",
    "adapters",
    "application",
    "domain"
]
exhaustive = true