name: Release process
# Releases on Pypi when a version tag is pushed.

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          allow-prereleases: true
      - name: Install build
        run: "python3 -m pip install build --user"
      - name: Build a binary wheel and a source tarball
        run: "python3 -m build --sdist --wheel --outdir dist/"
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN_IMPORT_LINTER }}
